ALL = bytefuck

FLAGS ?= -g -O3 -Wall -lhiredis -lpthread
CFLAGS ?= -g -O3 -Wall -lhiredis  -lpthread
CXXFLAGS ?= -g -O3 -Wall -lhiredis  -lpthread
CPPFLAGS ?= -g -O3 -Wall -lhiredis  -lpthread

all: $(ALL)

clean:
	rm -rf $(ALL) *.o
