# Generated by Django 2.0.1 on 2018-03-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='problem',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
