# Generated by Django 2.0.1 on 2018-09-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0002_auto_20180901_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='reference_function_rate',
            field=models.FloatField(default=0),
        ),
    ]
