# Generated by Django 2.0.1 on 2018-03-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0002_auto_20180301_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='fitness',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='population',
            name='max_generations',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='population',
            name='max_individuums',
            field=models.IntegerField(default=100),
        ),
    ]
