# Generated by Django 2.0.1 on 2018-09-01 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0003_species_reference_function_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencefunction',
            name='fitness_relative',
        ),
        migrations.RemoveField(
            model_name='referencefunction',
            name='memory_usage',
        ),
        migrations.RemoveField(
            model_name='referencefunction',
            name='program_steps',
        ),
    ]
