# Generated by Django 2.0.1 on 2018-03-01 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0005_auto_20180301_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='population',
            name='max_individuums',
        ),
        migrations.AddField(
            model_name='population',
            name='max_individuals',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='individual',
            name='population',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individuals', to='brainweb.Population'),
        ),
        migrations.AlterField(
            model_name='population',
            name='max_generations',
            field=models.IntegerField(default=3),
        ),
    ]
