# Generated by Django 2.0.1 on 2018-09-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0005_auto_20180907_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='individuals_created',
            field=models.BigIntegerField(default=0),
        ),
    ]
