# Generated by Django 2.0.1 on 2018-03-01 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0006_auto_20180301_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='fitness_evalcount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='individual',
            name='fitness_sum',
            field=models.FloatField(default=0),
        ),
    ]
