# Generated by Django 2.0.1 on 2018-03-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0007_auto_20180301_2328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individual',
            options={'ordering': ['fitness']},
        ),
        migrations.AddField(
            model_name='individual',
            name='codetokens',
            field=models.CharField(default='', max_length=200),
        ),
    ]
