# Generated by Django 2.0.1 on 2018-09-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0007_remove_species_usepriorknowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='code_compiled_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='species',
            name='max_compiled_code_length',
            field=models.BigIntegerField(default=20),
        ),
    ]
