# Generated by Django 2.0.1 on 2018-10-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0009_auto_20181003_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='sync_cross_p2p_at',
            field=models.BigIntegerField(default=200000),
        ),
        migrations.AddField(
            model_name='species',
            name='sync_cross_population_at',
            field=models.BigIntegerField(default=100000),
        ),
    ]
