# Generated by Django 2.0.1 on 2018-03-02 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0009_auto_20180302_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceFunction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('name', models.CharField(default='', max_length=200)),
                ('fitness', models.FloatField(blank=True, default=None, null=True)),
                ('fitness_sum', models.FloatField(default=0)),
                ('fitness_evalcount', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['fitness'],
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='autosync',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='code',
            field=models.CharField(default='..', max_length=200),
        ),
        migrations.AddField(
            model_name='referencefunction',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referencefunctions', to='brainweb.Problem'),
        ),
    ]
