# Generated by Django 2.0.1 on 2018-03-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0010_auto_20180302_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='autosync',
        ),
        migrations.AddField(
            model_name='problem',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
