# Generated by Django 2.0.1 on 2018-03-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0011_auto_20180302_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='population',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='individual',
            name='execution_counter',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='referencefunction',
            name='execution_counter',
            field=models.FloatField(default=0),
        ),
    ]
