# Generated by Django 2.0.1 on 2018-03-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0012_auto_20180303_0701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individual',
            options={'ordering': ['-fitness']},
        ),
        migrations.AddField(
            model_name='population',
            name='generation_count',
            field=models.IntegerField(default=3),
        ),
    ]
