# Generated by Django 2.0.1 on 2018-03-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0013_auto_20180303_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['-updated']},
        ),
        migrations.AddField(
            model_name='population',
            name='individual_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='population',
            name='max_populationsize',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='population',
            name='generation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='population',
            name='max_generations',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='population',
            name='max_individuals',
            field=models.IntegerField(default=-1),
        ),
    ]
