# Generated by Django 2.0.1 on 2018-03-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0015_auto_20180303_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='population',
            name='max_code_length',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='problem',
            name='default_max_code_length',
            field=models.IntegerField(default=-1),
        ),
    ]
