# Generated by Django 2.0.1 on 2018-03-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0016_auto_20180304_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='execution_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='referencefunction',
            name='execution_time',
            field=models.FloatField(default=0),
        ),
    ]
