# Generated by Django 2.0.1 on 2018-03-05 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0017_auto_20180305_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='population',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individuals', to='brainweb.Population'),
        ),
        migrations.AlterField(
            model_name='referencefunction',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencefunctions', to='brainweb.Problem'),
        ),
    ]
