# Generated by Django 2.0.1 on 2018-03-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0018_auto_20180305_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='population',
            name='max_steps',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='problem',
            name='default_max_steps',
            field=models.IntegerField(default=-1),
        ),
    ]
