# Generated by Django 2.0.1 on 2018-03-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0019_auto_20180310_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='step_counter',
            field=models.FloatField(default=0),
        ),
    ]
