# Generated by Django 2.0.1 on 2018-03-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0020_individual_step_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='codelength',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='individual',
            name='code',
            field=models.CharField(default='..', max_length=2000),
        ),
    ]
