# Generated by Django 2.0.1 on 2018-03-10 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0021_auto_20180310_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individual',
            options={'ordering': ['-fitness', 'code_length']},
        ),
        migrations.RenameField(
            model_name='individual',
            old_name='codelength',
            new_name='code_length',
        ),
    ]
