# Generated by Django 2.0.1 on 2018-03-10 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0022_auto_20180310_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individual',
            options={'ordering': ['-fitness', '-code_length']},
        ),
    ]
