# Generated by Django 2.0.1 on 2018-03-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0028_remove_individual_fitnessevalcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='population',
            name='min_code_length',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='problem',
            name='default_min_code_length',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='individual',
            name='code',
            field=models.CharField(default='..', max_length=20000),
        ),
    ]
