# Generated by Django 2.0.1 on 2018-03-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0030_auto_20180314_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('host', models.CharField(default='', max_length=200)),
                ('port', models.IntegerField(default=12345)),
            ],
        ),
        migrations.RemoveField(
            model_name='problem',
            name='online',
        ),
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
