# Generated by Django 2.0.1 on 2018-03-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0034_peer_supernode'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='failcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='peer',
            name='lastfail',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='peer',
            name='port',
            field=models.IntegerField(default=4141),
        ),
    ]
