# Generated by Django 2.0.1 on 2018-03-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0035_auto_20180316_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='parent_fitness',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='code',
            field=models.CharField(default='.', max_length=20000),
        ),
    ]
