# Generated by Django 2.0.1 on 2018-03-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0036_auto_20180317_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='population',
            name='average_fitness',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='population',
            name='best_code',
            field=models.CharField(default='', max_length=200000),
        ),
        migrations.AddField(
            model_name='population',
            name='best_fitness',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='code',
            field=models.CharField(default='.', max_length=200000),
        ),
    ]
