# Generated by Django 2.0.1 on 2018-03-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0037_auto_20180321_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='sync_to_database',
            field=models.BooleanField(default=False),
        ),
    ]
