# Generated by Django 2.0.1 on 2018-03-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0040_auto_20180322_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='average_execution_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='individual',
            name='average_inputbuffer_usage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='individual',
            name='average_program_steps',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='individual',
            name='inputbuffer_usage',
            field=models.FloatField(default=0),
        ),
    ]
