# Generated by Django 2.0.1 on 2018-03-24 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0041_auto_20180324_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individual',
            old_name='step_counter',
            new_name='program_steps',
        ),
        migrations.RenameField(
            model_name='referencefunction',
            old_name='step_counter',
            new_name='program_steps',
        ),
    ]
