# Generated by Django 2.0.1 on 2018-03-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0042_auto_20180324_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='memory_usage',
            field=models.FloatField(default=0),
        ),
    ]
