# Generated by Django 2.0.1 on 2018-03-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0043_individual_memory_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='average_memory_usage',
            field=models.FloatField(default=0),
        ),
    ]
