# Generated by Django 2.0.1 on 2018-03-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0044_individual_average_memory_usage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individual',
            options={'ordering': ['-fitness', 'code_length', 'average_program_steps']},
        ),
        migrations.AddField(
            model_name='population',
            name='average_execution_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='population',
            name='average_inputbuffer_usage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='population',
            name='average_memory_usage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='population',
            name='average_program_steps',
            field=models.FloatField(default=0),
        ),
    ]
