# Generated by Django 2.0.1 on 2018-03-24 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0045_auto_20180324_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individual',
            options={'ordering': ['-fitness', '-average_inputbuffer_usage', 'code_length']},
        ),
        migrations.AddField(
            model_name='referencefunction',
            name='average_execution_time',
            field=models.FloatField(default=0),
        ),
    ]
