# Generated by Django 2.0.1 on 2018-03-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0046_auto_20180324_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='average_output_size',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='individual',
            name='output_size',
            field=models.FloatField(default=0),
        ),
    ]
