# Generated by Django 2.0.1 on 2018-03-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0047_auto_20180325_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='average_input_size',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='individual',
            name='input_size',
            field=models.FloatField(default=0),
        ),
    ]
