# Generated by Django 2.0.1 on 2018-03-25 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0049_auto_20180325_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='population',
            name='max_code_length',
            field=models.IntegerField(default=20),
        ),
    ]
