# Generated by Django 2.0.1 on 2018-03-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0050_population_max_code_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencefunction',
            name='average_input_size',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='referencefunction',
            name='average_output_size',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='referencefunction',
            name='input_size',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='referencefunction',
            name='output_size',
            field=models.FloatField(default=0),
        ),
    ]
