# Generated by Django 2.0.1 on 2018-04-05 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0051_auto_20180325_0312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencefunction',
            options={'ordering': ['-fitness']},
        ),
    ]
