# Generated by Django 2.0.1 on 2018-04-10 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0052_auto_20180405_0051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individual',
            options={'ordering': ['-fitness', '-average_inputbuffer_usage', 'code_length', 'average_execution_time']},
        ),
    ]
