# Generated by Django 2.0.1 on 2018-05-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainweb', '0053_auto_20180410_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='example_input',
            field=models.CharField(default='', max_length=200000),
        ),
        migrations.AddField(
            model_name='individual',
            name='example_output',
            field=models.CharField(default='', max_length=200000),
        ),
    ]
